//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStepTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int Id { get; set; }
        public string text { get; set; }
        public bool @true { get; set; }
        public int question { get; set; }
    }
}
